# Generated by Django 3.1.4 on 2020-12-05 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('updated', models.DateTimeField(verbose_name='Updated')),
                ('deleted', models.DateTimeField(verbose_name='Deleted')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('updated', models.DateTimeField(verbose_name='Updated')),
                ('deleted', models.DateTimeField(verbose_name='Deleted')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('updated', models.DateTimeField(verbose_name='Updated')),
                ('deleted', models.DateTimeField(verbose_name='Deleted')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aei_user.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('updated', models.DateTimeField(verbose_name='Updated')),
                ('deleted', models.DateTimeField(verbose_name='Deleted')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
                ('user_ad', models.CharField(max_length=20, verbose_name='User AD')),
                ('pass_ad', models.CharField(max_length=20, verbose_name='Pass AD')),
                ('user_admin', models.CharField(max_length=20, verbose_name='User admin')),
                ('pass_admin', models.CharField(max_length=20, verbose_name='Pass admin')),
                ('user_nisira', models.CharField(max_length=20, verbose_name='Pass admin')),
                ('pass_nisira', models.CharField(max_length=20, verbose_name='Pass admin')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('anydesk', models.CharField(max_length=10, verbose_name='Anydesk')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aei_user.area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='area',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aei_user.zone'),
        ),
    ]
